import 'package:flutter/material.dart';

/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'deals_platform';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String EN = 'assets/locales/en.json';
  static const String FR = 'assets/locales/fr.json';
  static const String USER = 'assets/models/user.json';

}
